Suppress float conversion warnings for oneAPI (#172)
[631797c](https://github.com/openxla/xla/commit/631797c84cbb02e805ec89090214e8093fd8ba1d)
commit in XLA causes the following failure in oneAPI GPU build:

`external/org_brotli/c/enc/backward_references_hq.c:199:27: error:
implicit conversion between floating point types of different sizes
[-Werror,-Wimplicit-float-size-conversion]`

This PR fixes the failure by disabling warnings about implicit float
conversions.